name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: workflow_dispatch
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: echo "Hello from GitHub Actions!"

